### ISSUE TITLE
NPY package

### ISSUE THREAD

**Issue by marcomameli1992** [Jindi0/SAFE#4]
Dear can you explain how to obtain the npy array from the (Word,We) that you provide with the use of SIF?

We need to open each data in dataset?
For image how to do this operation?

**Comment by marcomameli1992** [comment]
In addition I downloaded your dataset but there are some images that can not be opened. There are any solution?

**Comment by Jindi0** [comment]
Hi, 
- We have updated the embedding method, please check the embedding branch.
- To use the image information, please use the "show and tell" tool to translate the image into a natural language sentence, then process the text (clean and embedding).
- We ignore the news with broken images because we need to make sure the content of visual information is not empty.
